name: Firebase Deploy

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - uses: actions/upload-artifact@main
        with:
          name: build
          path: build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@main
        with:
          name: build
          path: build
      - uses: firebase-tools/deploy@v1
        with:
          args: deploy --only hosting
        env:
          GCP_SA_KEY: "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC7lBM/khL4/2O+\nHv11uFln4UazfJHlWZA3B0ecUGKoDnhcLsy28ZZnM/Tk2+EkrF/ETfTpAlAVh4j5\ndxkAI6CAvbWlRIk7uG1pVf0fd29beTjwikOcKJfpIXUPPNOCtFc4aQzTMVbnKKGd\nBnqC1MfUtJzfKkG98tEpYuphVWeoXh4aJZMZf3lHqrRDenFKdyDgImoWWhKdMp8p\nnDfCcSnGO6wHbc9qFqhFP+xjvklInE5BL75QdoUWiHGMirJsK9fDBIJEt94sPmtt\nRBRzOgDofbGOVa2Lf0tj62qb6GmjNS14ZcP6NB6HZYL6sutJI2TeU6N5917jxOHv\nkALS/M3NAgMBAAECggEABWRRFf42bRGLm0RGcohSiuxhp7jNyXhvb02BGaABPfsb\nKuyDdkIahIFB/wQdBCdaTLPASvmwi0s355KCAEwwib1/nQO2fXt51aci8rEbB9eZ\nCJJeNX0V5Mh762y1rbz5AYZE1/CZTWVlw97oTZ4dLQ2QsXou+pf3ZYenh2sOODuI\n/tcpu5YqT01DD07zqYnBcMRDXi0dwfI+vHlMlBE+g1FNhVRljJd1Jq2aGTKRfq+v\ncwrnVq9jxFr4fB36jSaR9PbU3D2vRN/0Ay543Wf/AmhNEIxeC2REhONzilPNYxby\nqNyXjkOjebxk1Yw+npf4Ix5FVMYI5N9xtXNR2BS29wKBgQD3W/7jYQMOnRfek0gr\nU/+M2LuaCW7fhjICDIHS80JkteQhp4SmP2rasOyKOXLqMHMAIou3L57TPHRNiZoL\nncoDNBMZJgmRYGLQIyeGBgUtXSWBa7izUEoTKRYTvPXOZnY3bBXC1zkJ2UMoD5pd\nBhH8cUuzAAf+LkoaNUtidWcq8wKBgQDCIX13hH+C0IArEJxo6Uvv0lpcNbYkbXPk\n7RUtbah/F9dTHbgqRy9h7v//gutcBluFmd7XJV0rwo88e6QHv5Nwd+pM0lNRdDMA\nTseA6/fd+dQmJRdWLE7NZYfMoTSk2ucVa4RKCkou7LVEzF+VGez1Cm4u4/j7EsrP\nZbGBNtjUPwKBgQCRohcyVfaPzwuznnEaGW1Wxm/FZBJkBcVBkY2J3nDTjIeRDOi7\nXJETyqCpTOOMYBQFG1G4+499/JTY5c/NUQwT0MAByXROpDnpIxls/fRkXffr97kZ\n0YabO1BlNJZf+9FUFg3F1iMd2k2As5cFd8J1J1sTO0x5aVV1krUcddTU4wKBgF35\nclAh/svnfLPcJasPjGf6ry1F/vchWOHv9rl4BQIJG34ru9QTg5dn59rbmG2C0lkZ\nRGtntfOSCl6gB6aMkaX3Fp+7jQO4OVwjxqXdFK8K2izg9awMZNU/Gf7v5pkLMqQG\n2RIyavjOM22rdXWrCC8SroXaa9O2pCDDvKqtT0dnAoGAA7H/VRh6vlH8iJJ8Nt+n\npfoFjI6K+UNg9hvXrLQdkMlnI9GGeVxaD+ZFQo+5QYw9JA/2RuW51NBo6UE2+UYw\nVy1HUlLwhKDlbcjjo+lYP6V2cX0vfsXzi1C6iZf6tQYrMcFfxBuZxYCKLsbZhuc1\nyWDFoWvJ2j/u3DecY6LyWP0=\n-----END PRIVATE KEY-----\n"
          PROJECT_ID: tdp-reports-c4ee8
          CI: true
          FIREBASE_DEPLOY_TOKEN: ${{ secrets.FIREBASE_DEPLOY_TOKEN }}
