
name: Firebase Deploy

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - uses: actions/upload-artifact@main
        with:
          name: build
          path: build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@main
        with:
          name: build
          path: build
      - uses: firebase-tools/deploy@v1
        with:
          args: deploy --only hosting
        env:
          GCP_SA_KEY: ${{ secrets.Letest_Firebase_Service_Token }}
          PROJECT_ID: tdp-reports-c4ee8
          FIREBASE_DEPLOY_TOKEN: ${{ secrets.LETEST_FIREBASE_TOCKEN }}
